services:
  app:
    image: mcr.microsoft.com/devcontainers/java:17-bullseye

    volumes:
      - ..:/workspace:cached

    command: sleep infinity

    network_mode: service:postgres

    depends_on:
      - postgres

    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: appdb
      DB_USER: appuser
      DB_PASSWORD: apppass
      SPRING_PROFILES_ACTIVE: dev

  postgres:
    image: postgres:16-alpine
    restart: unless-stopped

    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init.sql:ro

    environment:
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: apppass
      POSTGRES_DB: appdb

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U appuser -d appdb"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  postgres-data:
